### ISSUE TITLE
XML web.config transform not working

### ISSUE THREAD

**Issue by Russweb** [sergeyzwezdin/magic-chunks#15]
When I try to alter a standard webconfig that looks like this:  

`<?xml version="1.0" encoding="utf-8"?> 
<configuration> 
   <configSections> 
         <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" /> 
     </configSections> 
     <connectionStrings> 
              <add name="DevOpsConn" connectionString="Data Source=mydatabase;Initial Catalog=DevOps;Persist Security Info=True;User ID=DevOpsUser;Password=foo" providerName="System.Data.SqlClient" />
          </connectionStrings>`

with this Transformation:  

configuration/connectionStrings/add[@name='DevOpsConn']/@connectionString = "Data Source=mydatabase;Initial Catalog=DevOps;Persist Security Info=True;User ID=$(DevOpsROSQLUser);Password=$(DevOpsROSQLUserPswd)"  

I get this release time error:  
System.ArgumentException: Invalid JSON primitive: configuration  

Yes...I've tried "auto detect" and "XML" as the file type. Both end the same way.
I've tried putting the entire statement in quotes, or each side of the statement in its own quotes.
Nothing will work.

**Comment by sergeyzwezdin** [comment]
For transformations you have to use JSON key-value dictionary. Try to use this one:

```json
{
   "configuration/connectionStrings/add[@name='DevOpsConn']/@connectionString": "Data Source=mydatabase;Initial Catalog=DevOps;Persist Security Info=True;User ID=$(DevOpsROSQLUser);Password=$(DevOpsROSQLUserPswd)"
}
```

Does it help?

**Comment by Russweb** [comment]
I tried that before, but I must have gotten the syntax wrong in some way.
That worked.
Thank you.

**Comment by sergeyzwezdin** [comment]
@Russweb 👍

**Comment by sergeyzwezdin** [comment]
@Russweb as it's resolved, coult you please update your posting at Reviews section at VSTS marketplace? 😺

**Comment by PremRaju** [comment]
I am getting this error for  xml tranformation.
--------------------------------------------------------
ConvertFrom-StringData : Data line '{' is not in 'name=value' format. 
At C:\Users\prebm\Desktop\Scripts\Appsettingautomation\AppsettingsConfigTransformations.ps1:22 char:17
+ $xformsAsHash = ConvertFrom-StringData -StringData $xformsAsStr
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ConvertFrom-StringData], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.ConvertFromStringDataCommand
 
Format-MagicChunks : Cannot bind argument to parameter 'transformations' because it is null.
At C:\Users\prebm\Desktop\Scripts\Appsettingautomation\AppsettingsConfigTransformations.ps1:23 char:60
+ ... mat-MagicChunks -path $destinationPath -transformations $xformsAsHash
+                                                             ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Format-MagicChunks], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Format-MagicChunks

My XML file
-------------------
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
       
    <add key="ElasticSearchUsername" value="elastic" />
    <add key="ElasticLogTimeDelay" value="15000" />
    <add key="DefaultTradeDataIndex" value="o_businessservicesauditlogs" />
  </appSettings>

</configuration>

trnaformfile
--------------
{
   "configuration/appSettings/add[@key='ElasticSearchUsername']/@value": "india"
}

**Comment by ttaylor29** [comment]
> For transformations you have to use JSON key-value dictionary. Try to use this one:
> 
> ```json
> {
>    "configuration/connectionStrings/add[@name='DevOpsConn']/@connectionString": "Data Source=mydatabase;Initial Catalog=DevOps;Persist Security Info=True;User ID=$(DevOpsROSQLUser);Password=$(DevOpsROSQLUserPswd)"
> }
> ```
> 
> Does it help?

How would I add in the provider name to this?
