### ISSUE TITLE
Extension is not available in tasks list

### ISSUE THREAD

**Issue by outofbounder** [sergeyzwezdin/magic-chunks#9]
TFS 2015 update 2 instance.  Extension says it has been installed to the project collection (confirm screen says "Already Installed".  Uninstall/reinstall does not work per previous closed issue...

**Comment by eeinworks8** [comment]
Same issue on our On-Premise TFS Server.

**Comment by eeinworks8** [comment]
So I got it to appear!  It turns out the task.json file has a minimum agent version of 1.95.1.  All of my agents were version 1.95.0.  I changed the task.json file to 1.95.0 and repackaged the vsix file and the task appeared.  I'm not sure if this extension truly needs agent version 1.95.1 or what the difference is between the two, but at least it shows up in the task list now.  Hope this helps.

**Comment by sergeyzwezdin** [comment]
@eeinworks8 do you use VS Online or TFS on premise?

**Comment by eeinworks8** [comment]
On premise with Update 2

**Comment by sergeyzwezdin** [comment]
@eeinworks8  Does it works correctly after changing to `1.95.0`?

**Comment by eeinworks8** [comment]
@sergeyzwezdin Yes it works great!
